<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Practical_2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Practical_2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Practical_2_files/libs/quarto-html/quarto.js"></script>
<script src="Practical_2_files/libs/quarto-html/popper.min.js"></script>
<script src="Practical_2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Practical_2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Practical_2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Practical_2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Practical_2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Practical_2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Practical_2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Practical_2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="infs-2049-experimental-design" class="level2">
<h2 class="anchored" data-anchor-id="infs-2049-experimental-design">INFS 2049 Experimental Design</h2>
<section id="joshua-chopin" class="level3">
<h3 class="anchored" data-anchor-id="joshua-chopin">Joshua Chopin</h3>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section">2025-01-09</h3>
<p><strong>(Student: Michael Hudson)</strong></p>
<hr>
<p>Last week’s practical was a bit unique in that it served as a return to programming in R. We very generally summarised and visualised a dataset to get a base understanding of the tools we will be using in this course. From now on, most practicals will follow a standard format, split into two parts. The first part will be illustrative examples of the concepts learned in the weeks course content. We will use one or more interesting datasets and show how the types of design you have learned can be implemented in R. In the second part of the practical you will receive a new dataset with a set of exercises for you to complete. For instance, this week we will learn the tools used to analyse independent and paired samples designs in R, using a separate dataset for each. Then you will be provided with a new dataset nand asked to use those tools to analyse the data.</p>
<p><strong>Effect of breakfast on mood and memory</strong></p>
<p>The first dataset we will be using today examines the effects of cereal bars for breakfast on mood and memory. Thirty two volunteers (16 male and 16 female, average age 22 years) were recruited and randomly assigned to two groups, one scheduled to have breakfast and the other to have no breakfast. In both testing sessions, volunteers rated various aspects of their mood using multiple visual analogue scales (e.g.&nbsp;Sad-Happy, Tense-Calm, Drowsy-Alert) displayed on a computer screen. An overall mood score was then derived for each participant. In addition, a free recall memory task was carried out during the second testing session.</p>
<p><strong>Q.</strong> Does this experiment use paired or independent samples?</p>
<p>Going forward we will use a standard formula for analysing experiments such as this one. That is; load the data, summarise and visualise, perform statistical analysis and conclude on the findings. This leads us to a question though, what are we trying to find?</p>
<p><strong>Q.</strong> Before reading on, what are two interesting hypotheses that we could form based on this experimental design? Define a null and alternative hypothesis for each.</p>
<p>The cereal bar dataset comes in the form of a .csv file so we will be using the readr package to load it. Hopefully your R installation already has the readr package from last week, but just in case, here is the installation command again, followed by the commands to load and inspect the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("readr")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>cerealdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data_raw/cereal.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 32 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Condition
dbl (3): Mood_Before, Mood_After, Recall

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cerealdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Condition Mood_Before Mood_After Recall
  &lt;chr&gt;           &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;
1 Bar              289.       298.      5
2 Bar              136.       196.      9
3 Bar              183.       167.      9
4 Bar              159.       132.     13
5 Bar              232.       253.     11
6 Bar              256.       259.      9</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cerealdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Condition          Mood_Before      Mood_After        Recall      
 Length:32          Min.   :120.1   Min.   :112.5   Min.   : 4.000  
 Class :character   1st Qu.:190.9   1st Qu.:178.2   1st Qu.: 6.000  
 Mode  :character   Median :231.3   Median :227.8   Median : 8.000  
                    Mean   :221.7   Mean   :224.9   Mean   : 7.844  
                    3rd Qu.:251.8   3rd Qu.:264.8   3rd Qu.: 9.000  
                    Max.   :323.0   Max.   :328.9   Max.   :15.000  </code></pre>
</div>
</div>
<p>There are four columns in the dataset. First the <em>condition</em> column indicates whether the individual received a bar or not, the <em>mood before</em> and <em>mood after</em> columns give the individuals mood score before and after breakfast time and finally the <em>recall</em> column provides their recall scores. The summary command showed us that over all the participants, the mean mood score increased after breakfast. Lets think about how that increase could be explained. Perhaps -</p>
<ul>
<li>mood stayed the same for those without a cereal bar and got better for those with it.</li>
<li>mood decreased for those without a bar, but got substantially better for those with a bar,</li>
<li>having a cereal bar did not effect mood, and people just get happier in the afternoon in general.</li>
</ul>
<p>all very reasonable hypotheses to make! Normally when designing such an experiment we would have a hypothesis in mind, hence the need for the exdperiment, and you have already taken a guess at what some potential hypotheses could be. Lets use the data to see if a hypothesis of a change in mood might be supported by this data. We will use a boxplot to get some idea of what the data looks like. First, I would like to add a new column to the dataset called <code>Mood_Diff</code>, which shows the difference in the before and after mood scores. Note that I have defined this variable as Mood_After-Mood_Before, meaning that positive values will mean the individual got happier and negative values will mean their mood decreased.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cerealdata<span class="sc">$</span>Mood_Diff <span class="ot">&lt;-</span> cerealdata<span class="sc">$</span>Mood_After <span class="sc">-</span> cerealdata<span class="sc">$</span>Mood_Before</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Mood_Diff <span class="sc">~</span> Condition, <span class="at">data =</span> cerealdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Practical_2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The boxplot makes it look pretty clear that those who had a cereal bar saw an increase in mood score. But is the difference statistically significant? That sounds like a good first hypothesis.</p>
<p>Null Hypothesis (<span class="math inline">\(H_0\)</span>): Having a breakfast cereal bar does not effect mood score</p>
<p><span class="math inline">\(H_0: \mu_0 - \mu_1 = 0\)</span></p>
<p>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>): Having a breakfast cereal bar does effect mood score</p>
<p><span class="math inline">\(H_0: \mu_0 - \mu_1 \neq 0\)</span></p>
<p>where <span class="math inline">\(\mu_0\)</span> is the mean of those who had a cereal bar and b<span class="math inline">\(\mu_1\)</span> is for those who did not. To test this we use <code>t.test</code> from the base R installation. For a t-test with two independent samples like this one the function can simply take two arguments, <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> which represent the two samples being tested. There are several ways to separate our data appropriately. One way would be to identify which rows of our dataset correspond to individuals who had bars and which didn’t. We can do this using the <code>which</code> command, then call the t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Wb <span class="ot">&lt;-</span> <span class="fu">which</span>(cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"Bar"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>Wnb <span class="ot">&lt;-</span> <span class="fu">which</span>(cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"No bar"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(cerealdata<span class="sc">$</span>Mood_Diff[Wb], cerealdata<span class="sc">$</span>Mood_Diff[Wnb])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  cerealdata$Mood_Diff[Wb] and cerealdata$Mood_Diff[Wnb]
t = 4.2716, df = 29.509, p-value = 0.0001851
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 23.35169 66.19435
sample estimates:
mean of x mean of y 
 25.58551 -19.18751 </code></pre>
</div>
</div>
<p>Alternatively, we can cut out the middle man, so to speak, and find these rows directly in the call to <code>t.test</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(cerealdata<span class="sc">$</span>Mood_Diff[cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"Bar"</span>],</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>       cerealdata<span class="sc">$</span>Mood_Diff[cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"No bar"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  cerealdata$Mood_Diff[cerealdata$Condition == "Bar"] and cerealdata$Mood_Diff[cerealdata$Condition == "No bar"]
t = 4.2716, df = 29.509, p-value = 0.0001851
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 23.35169 66.19435
sample estimates:
mean of x mean of y 
 25.58551 -19.18751 </code></pre>
</div>
</div>
<p>The output of the t-test tells us a number of things. First, with a p-value of 0.0001 we can reject the null hypothesis and conclude that consuming a breakfast cereal bar does alter mood at the 5% significance level (it is not included in our call to t-test, but the default value for conf.level, the confidence level parameter, is 0.95). We can see the mean difference in mood score before and after breakfast time of the two groups is 25.59 and -19.18, we got a rough idea of these values from the boxplot earlier. Finally, the output tells us with 95% confidence that the difference in mean mood score before and after breakfast between groups lies between 23.35 and 66.19.</p>
<p>Before moving on, we should check that our experiment had adequate <em>power</em>. To do so we will make use of the <code>pwr</code> package which can calculate power for both independent and paired sample t-tests using the <code>pwr.t.test</code> function. The function requires us to input <em>n</em>, the number of observations per sample, <em>d</em>, the effect size Cohen’s d and <em>sig.level</em>, the significance level we wish to use. Cohen’s d can be calculated manually, or we can simply use the effectsize package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("pwr")</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pwr' was built under R version 4.4.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("effectsize")</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'effectsize' was built under R version 4.4.2</code></pre>
</div>
</div>
<p>First we will calculate Cohen’s d, where we simply pass the two samples as input. Note that the <code>cohens_d</code> function outputs a number of variables, we just want to keep the d value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>cd <span class="ot">&lt;-</span> <span class="fu">cohens_d</span>(cerealdata<span class="sc">$</span>Mood_Diff[cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"Bar"</span>],</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>               cerealdata<span class="sc">$</span>Mood_Diff[cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"No bar"</span>])</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>cd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |       95% CI
------------------------
1.51      | [0.71, 2.29]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> cd<span class="sc">$</span>Cohens_d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we can call the power test function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">n =</span> <span class="dv">16</span>, <span class="at">d =</span> D, <span class="at">sig.level =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 16
              d = 1.510226
      sig.level = 0.05
          power = 0.9850448
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>From the power test we can conclude that the experiment used enough samoples to test this hypothesis.</p>
<p>Lets try another hypothesis test using the data.</p>
<p>Null Hypothesis (<span class="math inline">\(H_0\)</span>): Having a breakfast cereal bar does not improve recall</p>
<p><span class="math inline">\(H_0: \mu_0 - \mu_1 = 0\)</span></p>
<p>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>): Having a breakfast cereal bar does improve recall</p>
<p><span class="math inline">\(H_0: \mu_0 - \mu_1 \neq 0\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(cerealdata<span class="sc">$</span>Recall[cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"Bar"</span>],</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>       cerealdata<span class="sc">$</span>Recall[cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"No bar"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  cerealdata$Recall[cerealdata$Condition == "Bar"] and cerealdata$Recall[cerealdata$Condition == "No bar"]
t = 3.2667, df = 23.856, p-value = 0.003284
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.9890026 4.3859974
sample estimates:
mean of x mean of y 
   9.1875    6.5000 </code></pre>
</div>
</div>
<p>Again we can see a p-value less than 0.05, so it is safe to reject the null hypothesis. One point of interest though, is that the difference between groups seems to be smaller. At the bottom end of the 5% significance interval there is only a 0.98 increase in recall score between those who had a bar and those who did not. This is a little over 10% of the mean recall value across the dataset, whereas for mood score the bottom of our confidence interval had a much larger value. This indicates that while the difference is statistically significant, it may not be as substantial as the increase in mood.</p>
<p>Once again we can check the power of the experiment -</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>cd_recall <span class="ot">&lt;-</span> <span class="fu">cohens_d</span>(cerealdata<span class="sc">$</span>Recall[cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"Bar"</span>],</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                      cerealdata<span class="sc">$</span>Recall[cerealdata<span class="sc">$</span>Condition <span class="sc">==</span> <span class="st">"No bar"</span>])</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>cd_recall</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |       95% CI
------------------------
1.15      | [0.40, 1.90]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>D_recall <span class="ot">&lt;-</span> cd_recall<span class="sc">$</span>Cohens_d</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">n =</span> <span class="dv">16</span>, <span class="at">d =</span> D_recall, <span class="at">sig.level =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 16
              d = 1.154957
      sig.level = 0.05
          power = 0.8850346
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p><strong>Q.</strong> What does this power test tell us?</p>
<p><strong>Testing reflex blink-rate of the eyes</strong></p>
<p>The second dataset we are going to use in this practical comes from an experiment in which 12 subjects (people) were asked to steer a pencil along a moving track, in order to provide information on the reflex blink-rate of the eyes during visual motor tasks. Each subject was tested for two spells each of eight minutes, each spell having alternating periods of straight and oscillating track: the average blink-rate per minute was obtained for each subject for each type of track.</p>
<p><strong>Q.</strong> Before reading on, does this experiment use paired or independent samples?</p>
<p><strong>Q.</strong> Before reading on, formulate a hypothesis we could test using this dataset. Define a null and alternative hypothesis.</p>
<p>The data comes from a package called <code>PairedData</code> which contains data from a number of paired sample experiments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("PairedData")</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(PairedData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'PairedData' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: gld</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gld' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: mvtnorm</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'mvtnorm' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'mvtnorm'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:effectsize':

    standardize</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'PairedData'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:base':

    summary</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Blink"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Blink)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Subject Straight Oscillating
1     S01     24.0        15.0
2     S02     19.5         6.6
3     S03      8.2         1.9
4     S04      8.5         1.5
5     S05     12.1         1.1
6     S06      8.0         2.5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Blink)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Subject     Straight      Oscillating    
 S01    :1   Min.   : 5.50   Min.   : 0.500  
 S02    :1   1st Qu.: 7.80   1st Qu.: 0.975  
 S03    :1   Median : 8.35   Median : 1.750  
 S04    :1   Mean   :10.58   Mean   : 3.083  
 S05    :1   3rd Qu.:10.60   3rd Qu.: 2.650  
 S06    :1   Max.   :24.00   Max.   :15.000  
 (Other):6                                   </code></pre>
</div>
</div>
<p>From the summary of the blink data we can already see that there could be a difference in blink-rate when using a straight or oscillating track.</p>
<p><strong>Q.</strong> Create a boxplot for both the straight and oscillating track data. Make some notes about what you can see from the plot (Careful! The boxplot function won’t be called the same way it was before).</p>
<p>If you were able to make the boxplot you would have noticed a couple of outliers. These belong to Subject 1 and Subject 2 (i.e.&nbsp;the first two rows in the dataset), do you think these subjects should have been excluded from the analysis? Some outliers are okay, as long as they don’t stop our data from being normally distributed. This can be tested using the Shapiro-Wilk test, which R has implemented in the base stats package. If we have a look at each individual sample -</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(Blink<span class="sc">$</span>Oscillating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Blink$Oscillating
W = 0.63433, p-value = 0.0002106</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(Blink<span class="sc">$</span>Straight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Blink$Straight
W = 0.7773, p-value = 0.00523</code></pre>
</div>
</div>
<p>we can see that both tests returned a value less than 0.05, indicating that the data is not normally distributed. However, in a paired samples experiment, we are interested in the difference between samples, so instead, we should be testing the difference -</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(Blink<span class="sc">$</span>Straight <span class="sc">-</span> Blink<span class="sc">$</span>Oscillating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Blink$Straight - Blink$Oscillating
W = 0.94464, p-value = 0.5604</code></pre>
</div>
</div>
<p>which passes the test for normality. If the data did not pass the test we would need to consider some non-parametric alternatives to the t-test which do not rely on the underlying normal distribution. Back to the aim of the experiment and hopefully we arrived at the same hypothesis to test, which is -</p>
<p>Null Hypothesis (<span class="math inline">\(H_0\)</span>): The type of track does not effect blink rate</p>
<p><span class="math inline">\(H_0: \mu_{difference} = 0\)</span></p>
<p>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>): The type of track does effect blink rate</p>
<p><span class="math inline">\(H_0: \mu_{difference} \neq 0\)</span></p>
<p>We again use the <code>t.test</code> function to perform our t-test and check the results. Because our data now comes from a paired experiment we just need to add <code>paired = TRUE</code> to the function call.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Blink<span class="sc">$</span>Straight, Blink<span class="sc">$</span>Oscillating, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Blink$Straight and Blink$Oscillating
t = 9.7392, df = 11, p-value = 9.621e-07
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 5.805055 9.194945
sample estimates:
mean difference 
            7.5 </code></pre>
</div>
</div>
<p>As suspected, the p-value is incredibly small, indicating that we can reject the null hypothesis and be confident that the type of track has an effect on blink-rate.</p>
<p><strong>Q.</strong> Similar to the previous tests, what other notes can you make based on the results of the t-test?</p>
<p>As mentioned earlier, the same function can be used to calculate the power of a paired samples experiment, we just need to specify the type of experiment in the call to <code>pwr.t.test</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>cd_blink <span class="ot">&lt;-</span> <span class="fu">cohens_d</span>(Blink<span class="sc">$</span>Straight, Blink<span class="sc">$</span>Oscillating)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>cd_blink</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |       95% CI
------------------------
1.53      | [0.59, 2.43]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>D_blink <span class="ot">&lt;-</span> cd_blink<span class="sc">$</span>Cohens_d</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">n =</span> <span class="dv">12</span>, <span class="at">d =</span> D_blink, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">type =</span> <span class="st">"paired"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Paired t test power calculation 

              n = 12
              d = 1.525146
      sig.level = 0.05
          power = 0.9976126
    alternative = two.sided

NOTE: n is number of *pairs*</code></pre>
</div>
</div>
<p>That is a lot of power!</p>
<p><strong>Have a go on your own</strong></p>
<p>For the final part of the practical you will repeat the above procedures on your own, using a new dataset. This dataset gives the PSS (stress measurement) for 26 people in prison at the entry and at the exit. Part of these people were physically trained (Sport) during their imprisonment. You can think of this kind of like the cereal bar experiment, except instead of cereal bars some subjects played sport and instead of at the breakfast table the subjects were at prison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"PrisonStress"</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(PrisonStress)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Subject Group PSSbefore PSSafter
1      A1 Sport        25       13
2      A3 Sport        17       15
3      A4 Sport        12       13
4      A5 Sport        21       22
5      A6 Sport        29       25
6      A7 Sport        28       24</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(PrisonStress)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Subject       Group      PSSbefore        PSSafter    
 A1     : 1   Control:11   Min.   : 0.00   Min.   : 8.00  
 A2     : 1   Sport  :15   1st Qu.:15.50   1st Qu.:16.75  
 A3     : 1                Median :21.00   Median :21.50  
 A4     : 1                Mean   :20.73   Mean   :21.58  
 A5     : 1                3rd Qu.:27.00   3rd Qu.:26.75  
 A6     : 1                Max.   :44.00   Max.   :33.00  
 (Other):20                                               </code></pre>
</div>
</div>
<p><strong>Q.</strong> Does this experiment use independent or paired samples?</p>
<p><strong>Q.</strong> What can you gather from the summary?</p>
<p><strong>Q.</strong> Make a pair of boxplots of the data and note what you can see.</p>
<p><strong>Q.</strong> Does this data pass a test for normality?</p>
<p><strong>Q.</strong> What null and alternative hypothesis should be used here?</p>
<p><strong>Q.</strong> Perform the t-test for your hypothesis. Are the results as you expected?</p>
<p><strong>Q.</strong> Did the experiment have adequate power for this hypothesis? (Note: we need to use <code>pwr.t2n.test</code> when there are two samples with unequal <code>n</code>. It is called in the same way though, type <code>?pwr.t2n.test</code> for direction)</p>
<p>My Notes</p>
<p>https://docs.mathjax.org/en/latest/input/tex/macros/index.html</p>
<p>https://www.cmor-faculty.rice.edu/~heinken/latex/symbols.pdf</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>